#! /bin/bash

# Log everything from stdout into syslog, but have any output into stderr be mailed to admin
exec > >(/usr/bin/logger -t 'partioid-import-members')

/opt/syncope/partioid/import-members.sh -y
