#! /bin/bash

# Log everything from stdout into syslog, but have any output into stderr be mailed to admin
exec > >(/usr/bin/logger -t 'partioid-import-members')

/opt/partioid-scripts/bin/syncope-import-members -y
